# Generated by Django 5.0.4 on 2024-04-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('describe_tu_caso', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.CharField(choices=[('09:00', '09:00'), ('10:10', '10:10'), ('11:20', '11:20'), ('12:30', '12:30'), ('13:40', '13:40'), ('16:00', '16:00'), ('17:10', '17:10'), ('18:20', '18:20')], max_length=25)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
